config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'movies#index'

  # Movies search
  get 'movies/search', to: 'movies#search', as: 'search_movies'

  # Movie resources with nested routes for comments and favorites
  resources :movies, only: %i[index show new create edit update destroy] do
    # Favorite/unfavorite actions
    collection do
      post 'favorite'
      get 'favorites'
    end

    member do
      delete 'unfavorite'
      post 'add_comment'
      delete 'remove_comment'
      get 'edit_comment/:comment_id', to: 'movies#edit_comment', as: 'edit_comment'
      patch 'update_comment/:comment_id', to: 'movies#update_comment', as: 'update_comment'
    end
  end
end

app/models/movie.rb
class Movie
  include Mongoid::Document
  include Mongoid::Timestamps

  field :imdb_id, type: String
  field :title, type: String
  field :year, type: String
  field :genre, type: String
  field :director, type: String
  field :synopsis, type: String
  field :poster, type: String
  field :comments, type: Array, default: []

  validates :imdb_id, presence: true, uniqueness: true

  has_and_belongs_to_many :favorited_by_users, class_name: 'User'

  def add_comment(user, content)
    comments << { _id: BSON::ObjectId.new, user_name: user.name, content: content, created_at: Time.now.utc }
    save
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :name, type: String
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  has_and_belongs_to_many :favorite_movies, class_name: 'Movie'

  validates :name, presence: true, length: { minimum: 2 }

  include Mongoid::Timestamps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if current_user
      @movies = current_user.favorite_movies.page(params[:page]).per(20)
    else
      redirect_to new_user_session_path, alert: 'You need to be logged in to view your favorite movies.'
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: 'Filme adicionado aos favoritos.'
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Filme atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, notice: 'Filme removido dos favoritos.'
  end

  def search
    @movies = if params[:query].present?
                OmdbService.search_movies(params[:query])
              else
                []
              end
  end

  def add_comment
    @movie = Movie.find(params[:id])

    if params[:comment].present?
      @movie.add_comment(current_user, params[:comment])
      flash[:success] = 'Comment added successfully!'
    else
      flash[:error] = 'Comment cannot be empty.'
    end

    redirect_to movie_path(@movie)
  end

  def remove_comment
    @movie = Movie.find(params[:id])
    comment_id = params[:comment_id]
    comment = @movie.comments.find { |c| c['_id'].to_s == comment_id }

    if comment
      @movie.comments.delete(comment)
      @movie.save
      flash[:success] = 'Comment deleted successfully!'
    else
      flash[:error] = 'Comment not found.'
    end

    redirect_to movie_path(@movie)
  end

  def favorite
    movie_data = OmdbService.get_movie_details(params[:imdb_id])

    movie = Movie.find_or_create_by(imdb_id: movie_data['imdbID']) do |m|
      m.title = movie_data['Title']
      m.year = movie_data['Year']
      m.genre = movie_data['Genre']
      m.director = movie_data['Director']
      m.synopsis = movie_data['Plot']
      m.poster = movie_data['Poster']
    end

    current_user.favorite_movies << movie unless current_user.favorite_movies.include?(movie)

    redirect_to movies_path, notice: 'Filme adicionado aos favoritos.'
  end

  def favorites
    @movies = current_user.favorite_movies
  end

  def unfavorite
    movie = Movie.find(params[:id])

    if current_user.favorite_movies.include?(movie)
      current_user.favorite_movies.delete(movie)
      flash[:notice] = 'Filme removido dos favoritos.'
    else
      flash[:alert] = 'Filme não encontrado nos favoritos.'
    end

    redirect_to movies_path
  end

  def edit_comment
    @movie = Movie.find(params[:id])
    @comment = @movie.comments.find { |c| c['_id'].to_s == params[:comment_id] }

    return unless @comment.nil?

    redirect_to movie_path(@movie), alert: 'Comentário não encontrado.'
  end

  def update_comment
    @movie = Movie.find(params[:id])
    @comment = @movie.comments.find { |c| c['_id'].to_s == params[:comment_id] }

    if @comment.nil?
      redirect_to movie_path(@movie), alert: 'Comentário não encontrado.'
    else
      @comment['content'] = params[:content]

      if @movie.save
        redirect_to movie_path(@movie), notice: 'Comentário atualizado com sucesso!'
      else
        redirect_to movie_path(@movie), alert: 'Erro ao atualizar o comentário.'
      end
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :year, :genre, :director, :synopsis, :user_comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <%= yield :head %>
  </head>
  <body class="bg-dark text-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-black">
      <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fas fa-film me-2"></i>MovieBox
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link" do %>
                <i class="fas fa-home me-1"></i> Home
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <span class="nav-link">Welcome, <%= current_user.name %></span>
              </li>
              <li class="nav-item">
                <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-link nav-link", data: { confirm: "Tem certeza que deseja sair?" } do %>
                  <i class="fas fa-sign-out-alt me-1"></i> Leave
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link" do %>
                  <i class="fas fa-sign-in-alt me-1"></i> Enter
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Editar Comentário do Filme</h1>

<%= form_with model: @movie, local: true do |form| %>
  <% if @movie.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_comment, 'Comentário' %>
    <%= form.text_area :user_comment, class: 'form-control' %>
  </div>

  <%= form.submit 'Atualizar Comentário', class: 'btn btn-success' %>
<% end %>

<%= link_to 'Voltar', movie_path(@movie), class: 'btn btn-secondary' %>

app/views/movies/edit_comment.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-8">
      <h3 class="text-white mb-3">Edit Comment</h3>
      <%= form_tag update_comment_movie_path(@movie, comment_id: @comment["_id"]), method: :patch, local: true do %>
        <div class="mb-3">
          <%= label_tag :content, "Comment:", class: "form-label text-white" %>
          <%= text_area_tag :content, @comment['content'], class: "form-control bg-dark text-white", rows: 3, placeholder: "Edit your comment..." %>
        </div>
        <%= submit_tag "Update Comment", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<%= render 'movies/partials/search_form' %>
<% if @movies.any? %>
  <h3 class="text-white mb-4">Favorite Movies</h3>
  <div class="row g-4">
    <% @movies.each do |movie| %>
      <%= render 'movies/partials/movie_card', movie: movie %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center mt-4">
    <%= paginate @movies %>
  </div>
<% else %>
  <%= render 'movies/partials/no_movies_message' %>
<% end %>

app/views/movies/new.html.erb
<h1>Adicionar Filme aos Favoritos</h1>

<%= form_with model: @movie, local: true do |form| %>
  <% if @movie.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, 'Título' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :year, 'Ano' %>
    <%= form.text_field :year, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :genre, 'Gênero' %>
    <%= form.text_field :genre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :director, 'Diretor' %>
    <%= form.text_field :director, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :synopsis, 'Sinopse' %>
    <%= form.text_area :synopsis, class: 'form-control' %>
  </div>

  <%= form.submit 'Adicionar Filme', class: 'btn btn-success' %>
<% end %>
<%= link_to 'Voltar', movies_path, class: 'btn btn-secondary' %>

app/views/movies/partials/_comment_form.html.erb
<%= form_with model: @movie, local: true, class: 'mb-4' do |form| %>
  <div class="mb-3">
    <%= form.label :user_comment, 'Add a comment', class: 'form-label' %>
    <%= form.text_area :user_comment, class: 'form-control bg-dark text-white', rows: 3 %>
  </div>
  <%= form.submit 'Save Comment', class: 'btn btn-primary' %>
<% end %>

app/views/movies/partials/_movie_actions.html.erb
<div class="d-flex gap-2">
  <%= link_to 'Edit Movie', edit_movie_path(@movie), class: 'btn btn-warning' %>
  <%= link_to 'Back', movies_path, class: 'btn btn-outline-light' %>
</div>

app/views/movies/partials/_movie_card.html.erb
<div class="col-sm-6 col-lg-4 col-xl-3">
  <div class="movie-card card bg-black border-0 h-100 rounded-4 shadow-lg">
    <div class="poster-wrapper position-relative">
      <%= image_tag movie.poster, 
          class: "card-img-top rounded-top-4",
          style: "height: 180px; object-fit: cover;" %>
      <div class="poster-overlay">
        <%= link_to movie_path(movie), class: 'btn btn-light btn-lg rounded-circle' do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
    </div>
    <div class="card-body d-flex flex-column p-3">
      <h5 class="card-title text-white mb-1"><%= movie.title %></h5>
      <p class="card-text text-light-gray mb-2 flex-grow-1 mt-0"><%= movie.synopsis.truncate(100) %></p>
      <div class="d-flex gap-2 mt-auto">
        <%= link_to movie_path(movie), class: 'btn btn-outline-light flex-grow-1' do %>
          <i class="fas fa-info-circle me-2"></i>Details
        <% end %>
        <%= button_to unfavorite_movie_path(movie), 
            method: :delete,
            class: "btn btn-outline-danger flex-grow-1" do %>
          <i class="fas fa-heart-broken me-2"></i>Remove
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/partials/_movie_details.html.erb
<h1 class="text-white mb-4"><%= @movie.title %></h1>
<div class="card bg-dark text-white mb-4">
  <div class="card-body">
    <p><strong>Year:</strong> <%= @movie.year %></p>
    <p><strong>Genre:</strong> <%= @movie.genre %></p>
    <p><strong>Director:</strong> <%= @movie.director %></p>
    <p><strong>Synopsis:</strong> <%= @movie.synopsis %></p>
  </div>
</div>

app/views/movies/partials/_no_movies_message.html.erb
<div class="no-movies-message d-flex align-items-center justify-content-center p-4 rounded-3 shadow-lg text-center">
  <i class="fas fa-star me-3"></i>
  <p class="text-white mb-0">Start saving your favorite movies, do a search!</p>
</div>

app/views/movies/partials/_search_form.html.erb
<div class="movie-app min-vh-100">
  <div class="container py-5">
    <div class="search-section mb-5">
      <div class="card bg-black border-0 rounded-4 shadow">
        <div class="card-body p-4">
          <h3 class="text-white mb-4">Search Movies</h3>
          <%= form_with url: search_movies_path, method: :get, local: true do |form| %>
            <div class="input-group input-group-lg">
              <%= form.text_field :query, 
                  class: 'form-control bg-dark text-white border-secondary', 
                  placeholder: 'Enter movie title...',
                  style: 'border-right: none;' %>
              <button class="btn btn-primary px-4" type="submit">
                <i class="fas fa-search me-2"></i>Search
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/movies/partials/_search_results.html.erb
<% @movies.each do |movie| %>
  <div class="col-6 col-sm-4 col-md-3 col-lg-2">
    <div class="card bg-dark text-white h-100">
      <img src="<%= movie['Poster'] %>" class="card-img-top" alt="<%= movie['Title'] %>" style="height: 250px; object-fit: cover;">
      <div class="card-body d-flex flex-column">
        <h6 class="card-title mb-3" style="height: auto; line-height: 1.2; white-space: normal; overflow: hidden; text-overflow: ellipsis;">
          <%= movie['Title'] %> (<%= movie['Year'] %>)
        </h6>
        <div class="mt-auto">
          <%= button_to favorite_movies_path, method: :post, params: { imdb_id: movie['imdbID'], title: movie['Title'], year: movie['Year'], genre: movie['Genre'], director: movie['Director'], synopsis: movie['Plot'], poster: movie['Poster'] }, class: 'btn btn-primary w-100' do %>
            <i class="fas fa-heart me-2"></i>Add to Favorites
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/search.html.erb
  <%= render 'movies/partials/search_form' %>

  <% if @movies.present? %>
    <h3 class="text-white mb-4">Search Results</h3>
    <div class="row g-4">
      <%= render 'movies/partials/search_results', movies: @movies %>
    </div>
  <% else %>
    <div class="no-movies-message d-flex align-items-center justify-content-center p-4 rounded-3 shadow-lg text-center">
      <i class="fas fa-exclamation-triangle me-3"></i>
      <p class="text-white mb-0">No movies found. Please try another search.</p>
    </div>
  <% end %>

app/views/movies/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-4">
      <img src="<%= @movie.poster %>" alt="<%= @movie.title %>" class="img-fluid rounded-4 shadow">
    </div>
    <div class="col-md-8">
      <%= render 'movies/partials/movie_details', movie: @movie %>
      <h3 class="text-white mb-4">User Comments</h3>
      <div class="comment-form-container mb-5">
        <%= form_with url: add_comment_movie_path(@movie), method: :post, local: true, class: "comment-form" do |form| %>
          <div class="mb-3 position-relative">
            <%= form.text_area :comment, class: "form-control bg-dark text-white", rows: 3, placeholder: "Share your thoughts about the movie...", id: "commentTextarea" %>
          </div>
          <%= form.submit "Post Comment", class: "btn btn-primary" %>
        <% end %>
      </div>
      <% if @movie.comments.any? %>
        <div class="comments-list mt-4">
          <h5 class="text-white mb-4">Previous Comments</h5>
          <% @movie.comments.each do |comment| %>
            <div class="comment-card mb-4">
              <div class="comment-header d-flex align-items-center mb-2">
                <div class="user-avatar"><%= comment["user_name"].first.upcase %></div>
                <div class="user-info ml-3">
                  <strong class="text-white"><%= comment["user_name"] %></strong>
                  <small class="text-muted d-block"><%= comment["created_at"].strftime("%d %b %Y, %H:%M") %></small>
                </div>
              </div>
              <p class="comment-content mb-3"><%= comment["content"] %></p>
              <% if current_user && current_user.name == comment["user_name"] %>
                <div class="comment-actions">
                  <%= link_to edit_comment_movie_path(@movie, comment_id: comment["_id"]), class: 'btn btn-outline-light btn-sm', style: 'margin-right: 5px;' do %>
                    <i class="fas fa-edit"></i> Edit
                  <% end %>
                  <%= button_to remove_comment_movie_path(@movie, comment_id: comment["_id"]), method: :delete, class: 'btn btn-outline-danger btn-sm', form: { style: 'display: inline-block; margin-left: 5px;' } do %>
                    <i class="fas fa-trash-alt"></i> Delete
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>